# use time make(....) to find the execution time

cn=

all: 1

1:
	javac -cp ca2/ CA02.java	
	java CA02 < ${cn}	> out.txt

2:
	javac -cp ca2/ Insertion.java	
	java Insertion < ${cn} > out.txt

clean:
	sudo rm ca2/*
